Imports System.IO

Public Class Consulta
    Inherits System.Web.UI.MasterPage
    Private Path, archivo As String
    Dim s As String

#Region "Eventos"
    Public Event btnBuscar_Click(ByVal sender As Object, ByVal e As EventArgs)
    Public Event btnNuevo_Click(ByVal sender As Object, ByVal e As EventArgs)
    Public Event btnImprimir_Click(ByVal sender As Object, ByVal e As EventArgs)
    Public Event btnExportar_Click(ByVal sender As Object, ByVal e As EventArgs)

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        AddHandler Master.PreRender, AddressOf Page_PreRender
    End Sub
    Private Sub Page_PreRender(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.PreRender
        btnNuevo.Enabled = Master.Alta
    End Sub

    Protected Sub btnBuscar_Click1(ByVal sender As Object, ByVal e As EventArgs) Handles btnBuscar.Click
        RaiseEvent btnBuscar_Click(sender, e)
    End Sub

    Protected Sub btnNuevo_Click1(ByVal sender As Object, ByVal e As EventArgs) Handles btnNuevo.Click
        RaiseEvent btnNuevo_Click(sender, e)
    End Sub

    Private Sub btnExportar_Click1(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnExportar.Click
        RaiseEvent btnExportar_Click(sender, e)
    End Sub
#End Region

#Region "Metodos"
    Public Property setNuevoVisible()
        Get
            Return Me.btnNuevo.Visible
        End Get
        Set(ByVal value)
            Me.btnNuevo.Visible = value
        End Set
    End Property

    Public Property setExportarVisible()
        Get
            Return Me.btnExportar.Visible
        End Get
        Set(ByVal value)
            Me.btnExportar.Visible = value
        End Set
    End Property
    Public Sub Exportar(ByVal grid As GridView, ByVal Filtros As DataTable, ByVal nombreMantenimiento As String)

        Dim ge As New GenExcell()
        archivo = nombreMantenimiento + ".xls"
        grid.AutoGenerateDeleteButton = False
        grid.AutoGenerateEditButton = False
        grid.AutoGenerateSelectButton = False

        Path = System.IO.Path.GetTempPath().ToString()
        Dim Dir As New System.IO.DirectoryInfo(Path)
        If Not Dir.Exists Then
            System.IO.Directory.CreateDirectory(Path)
        End If
        If System.IO.File.Exists((Path + "/" + archivo)) Then
            System.IO.File.Delete((Path + "/" + archivo))
        End If
        archivo = archivo.Replace(" ", "_")
        ge.DoExcell(Path + "/" + archivo, grid, nombreMantenimiento, Filtros)
        Response.ContentType = "application/octet-stream"
        Response.AddHeader("Content-Disposition", "attachment; filename=" + archivo)
        Response.WriteFile((Path + "/" + archivo))
    End Sub 'Exportar 'Dir.Delete(true);

    Friend Class GenExcell '
        Private w As StreamWriter

        Public Function DoExcell(ByVal ruta As String, ByVal grid As GridView, ByVal nombreMantenimiento As String, ByVal Filtros As DataTable) As Integer
            grid.AllowPaging = False
            Dim fs As New FileStream(ruta, FileMode.Create, FileAccess.ReadWrite)
            w = New StreamWriter(fs)
            EscribeCabecera(grid, nombreMantenimiento, Filtros)
            Dim tbl As DataTable = grid.DataSource
            Dim r As GridViewRow

            For Each r In grid.Rows
                EscribeLinea(r, grid.Columns.Count)
            Next r

            EscribePiePagina()
            w.Close()
            Return 0
        End Function 'DoExcell


        Public Sub EscribeCabecera(ByVal grid As GridView, ByVal nombreMantenimiento As String, ByVal Filtros As DataTable)
            Dim sFiltro As String = ""
            Dim iNumFiltros As Integer
            Dim html As New StringBuilder()

            html.Append("<!DOCTYPE HTML PUBLIC ""-//W3C//DTDHTML 4.0 Transitional//EN"">")
            html.Append("<html>")
            html.Append("  <head>")
            html.Append("<title>CODEX</title>")
            html.Append("<meta http-equiv=""Content-Type""content=""text/html; charset=UTF-8"" />")
            html.Append("  </head>")
            html.Append("<body>")
            html.Append("<p>")
            html.Append("<table>")
            html.Append("<tr>")
            html.Append("</tr>")
            html.Append("<tr>")
            html.Append("</tr>")
            html.Append("<tr style=""font-weight:bold;horizontalAlignment:center;font-size:16px;color: black;"">")
            html.Append("<td></td>")
            html.Append("<td></td>")
            html.Append(("<td font-weight:bold;horizontalAlignment:center;font-size:20px>" + nombreMantenimiento + "</td>"))
            html.Append("</tr>")
            'filtros
            iNumFiltros = Filtros.Rows.Count
            sFiltro = sFiltro + "<td></td>"
            Dim i As Integer
            For i = 0 To iNumFiltros - 1
                If Filtros.Rows(i).Item(1).ToString <> "" Then
                    sFiltro = ""
                    sFiltro = sFiltro + "<td></td><td>" + Filtros.Rows(i).Item(0).ToString + "</td>"
                    sFiltro = sFiltro + "<td>" + Filtros.Rows(i).Item(1).ToString + "</td>"
                    html.Append(("<tr >" + sFiltro + "</tr>"))
                End If
            Next i
            sFiltro = sFiltro + "<td></td>"

            html.Append("<tr>")
            html.Append("</tr>")

            html.Append("<tr style=""font-weight:bold;font-size: 13px;color: white;"">")

            html.Append("<td></td>")
            'Dim i As Integer
            For i = 0 To grid.Columns.Count - 1
                If grid.Columns(i).HeaderText <> "" Then
                    html.Append(("<td bgcolor=""DarkBlue""> " + grid.Columns(i).HeaderText + " </td>"))
                End If
            Next i
            'html.Append("<td bgcolor=\"Blue\">Iteración:</td>");
            html.Append("</tr>")
            w.Write(html.ToString())
        End Sub 'EscribeCabecera

        Public Sub EscribeLinea(ByVal r As GridViewRow, ByVal numColumnas As Integer)
            Dim bgColor As String = ""
            Dim fontColor As String = ""
            Dim sFilas As String = ""
            bgColor = " bgcolor=""LightBlue"" "
            fontColor = " style=""font-size: 12px;color: black;"" "
            sFilas = "<td></td>"
            Dim i As Integer

            For i = 0 To numColumnas - 1
                's = r.Cells(i).Controls.Item(0).
                If r.Cells(i).Controls.Count = 0 Then
                    sFilas = sFilas + "<td {0} {1}>" + r.Cells(i).Text + "</td>"
                Else
                    numColumnas = numColumnas + 1
                End If
            Next i
            w.Write("<tr >" + sFilas + "</tr>") '

        End Sub 'EscribeLinea

        Public Sub EscribePiePagina()
            Dim html As New StringBuilder()
            html.Append("  </table>")
            html.Append("</p>")
            html.Append(" </body>")
            html.Append("</html>")
            w.Write(html.ToString())
        End Sub 'EscribePiePagina
    End Class 'GenExcell
#End Region

    
    
    
End Class