<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="WfmExpediente_List.aspx.vb" Inherits="smx.WfmExpedientes_List" MasterPageFile="~/Consulta.Master" %>

<%@ MasterType VirtualPath="~/Consulta.Master"%>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<%@ Register src="~/Controles/TextBox.ascx" tagname="TextBox" tagprefix="uc1" %>
<%@ Register src="~/Controles/ComboBox.ascx" tagname="ListBox" tagprefix="uc2" %>

<%@ Register src="~/Controles/ComboBox.ascx" tagname="ComboBox" tagprefix="uc2" %>
<%@ Register src="~/Controles/DateControl.ascx" tagname="DateControl" tagprefix="uc3" %>


<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>


<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="ContentPlaceHolder2" >

    <div class="DD" >
    <div style="background-position: left top; border: 1px solid #F5F5F5; width: 235px; position: absolute; top: 150px; left: 5px; height: 95%; background-image: url('../../Imagenes/ExplorerNav.jpg'); border:thin;  background-attachment: inherit; ">

        <asp:TreeView ID="tvData" runat="server" BorderStyle="None" BorderWidth="1px" NodeIndent="7" Width="235px" AutoGenerateDataBindings="False" CollapseImageToolTip="" EnableTheming="False">
            <HoverNodeStyle Font-Underline="False" BackColor="#99CCFF" BorderColor="#6699FF" BorderStyle="Solid" BorderWidth="1px" />
            <Nodes>
                <asp:TreeNode Expanded="True" SelectAction="Expand" Selected="True" Text="Mis Expedientes" Value="Mis Expedientes">
                    <asp:TreeNode Text="Sin Recibir" Value="Sin Recibir"></asp:TreeNode>
                    <asp:TreeNode Text="Sin Enviar" Value="Sin Enviar"></asp:TreeNode>
                    <asp:TreeNode Text="Enviado Sin Recibir" Value="Enviado Sin Recibir"></asp:TreeNode>
                </asp:TreeNode>
            </Nodes>
            <NodeStyle Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" />
            <ParentNodeStyle Font-Bold="True" ForeColor="#5555DD" />
            <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" BackColor="#CC99FF" />
        </asp:TreeView>

        <br />

</div>

    <div style="position: absolute; top: 152px; left: 250px; height: 83%;">
         <table class="style1" style="width: 936px">
        <tr>
            <td class="style4" style="width: 148px">
                Numero de Expediente
            </td>
            <td align="left">
            <uc1:TextBox ID="tbxExpediente" runat="server" MaxLength="17" />
	    <td style="width: 144px">
                Número de Apoderado:
            </td>
            <td>
                <uc1:TextBox ID="txtCodigoApo" runat="server" FieldName="CodigoApoderado" 
                    MaxLength="60" width="240" />
            </td>
            <td class="style5" style="width: 813px">
                &nbsp;</td>
                    </tr>
        <tr>
            <td class="style4" style="width: 148px">
                Numero de Dictamen
            </td>
            <td>
                <uc1:TextBox ID="txtNumDictamen" runat="server" FieldName="NumeroDictamen" />
            </td>
            <td style="width: 144px">
                Solicitante
            </td>
            <td>
                <uc1:TextBox ID="txtSolicitante" runat="server" FieldName="NombreSolicitante" 
                    MaxLength="60" width="240" />
            </td>
            <td class="style5" style="width: 813px">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" style="width: 148px">
                Numero de Resolucion
            </td>
            <td>
                <uc1:TextBox ID="txtNumResolucion" runat="server" FieldName="NumeroResolucion" />
            </td>
            <td style="width: 144px">
                Encargado
            </td>
            <td>
                <uc1:TextBox ID="txtEncargado" runat="server" FieldName="NombreEncargado" 
                    MaxLength="60" width="240" />
            </td>
            <td class="style5" style="width: 813px">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" style="width: 148px">
                Servicio
            </td>
            <td>
                <uc2:ComboBox ID="cboServicioFiltro" runat="server" AutoFill="True" FieldName="idServicio"
                    idFieldName="ID" postBack="True" TableName="Servicios" textFieldName="Nombre"  />
            </td>
            <td style="width: 144px">
                SubServicio
            </td>
            <td>
                <uc2:ComboBox ID="cboSubServicio" runat="server" AutoFill="True" FieldName="idSubServicio"
                    idFieldName="Codigo" idParentComboBox="idServicio" 
                    TableName="SubServicios" textFieldName="Nombre"
                    AditionalCondition="indEstado='A'" postBack="False" />
            </td>
            <td class="style5" style="width: 813px">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" style="width: 148px">
                Departamento
            </td>
            <td>
                <uc2:ComboBox ID="cboDepartamento" runat="server" AutoFill="True" FieldName="idDepartamento"
                    idFieldName="id" Obligatorio="False" TableName="Departamento" textFieldName="Nombre"
                    postBack="True" />
            </td>
            <td style="width: 144px">
                Municipio
            </td>
            <td>
                <uc2:ListBox ID="cboMunicipio" runat="server" AutoFill="False" FieldName="idMunicipio"
                    idFieldName="id" idParentComboBox="idDepartamento" TableName="Municipio" textFieldName="Nombre" />
            </td>
            <td class="style5" style="width: 813px">
            </td>
        </tr>
        <tr>
            <td class="style4" style="width: 148px">
                Fecha Inicial
            </td>
            <td>
                <uc3:DateControl ID="dtcFechaDesde" runat="server" FechaHora="False" 
                    FieldName="FechaInicio" Obligatorio="False" />
            </td>
            <td style="width: 144px">
                Fecha Final
            </td>
            <td>
                <uc3:DateControl ID="dtcFechaHasta" runat="server" FechaHora="False" 
                    FieldName="FechaFinal" Obligatorio="False" />
            </td>
            <td class="style5" style="width: 813px">
            </td>
        </tr>
        <tr>
            <td class="style4" style="width: 148px; height: 1px;">
                Asignado a:</td>
            <td class="style5" style="height: 1px;">
                        <telerik:RadDropDownTree ID="cboEmpleado" runat="server" CheckNodeOnClick="True" Culture="es-ES" DataFieldID="" DataFieldParentID="" DataTextField="" DataValueField="" EnableFiltering="True" ExpandNodeOnSingleClick="True" Height="16px" OnClientEntryAdded="onEntryAdded" OnClientEntryAdding="OnClientEntryAdding1" Width="183px" Skin="Office2007">
                            <DropDownSettings AutoWidth="Enabled" CloseDropDownOnSelection="True" Height="270px" Width="120px" />
                            <FilterSettings Highlight="Matches" EmptyMessage="No hay resultados..." Filter="Contains" MinFilterLength="3" />
                        </telerik:RadDropDownTree>
                    <br />
            </td>
            <td style="width: 144px; height: 1px;">
            </td>
            <td class="style5" style="height: 1px;">
                <asp:RadioButtonList ID="rbtnList" runat="server" RepeatColumns="2" Width="441px">
                    <asp:ListItem Selected="True" Value="1">Fecha de Ingreso del Expediente</asp:ListItem>
                    <asp:ListItem Value="2">Fecha del Último Estado</asp:ListItem>
                    <asp:ListItem Value="3">Fecha de Emisión Resolución</asp:ListItem>
                    <asp:ListItem Value="4">Fecha de Emisión de Dictámen</asp:ListItem>
                </asp:RadioButtonList>
            </td>
            <td class="style5" style="width: 813px; height: 1px;">
            </td>
        </tr>
        <tr>
            <td class="style2" colspan="4">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" CssClass="mGrid" 
                    AlternatingRowStyle-CssClass="alt" AutoGenerateColumns="False" CellPadding="3" DataKeyNames="Id" EmptyDataText="No se encontraron registros" PageSize="6" BorderStyle="Solid" BorderWidth="1px" CellSpacing="2" Width="241px" Height="250px">
<AlternatingRowStyle CssClass="alt"></AlternatingRowStyle>
                    <Columns>
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="False" CommandName="Select"
                                    Text="Seguimiento"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="lnkEditar" runat="server" CausesValidation="False" CommandName="Edit"
                                    Text="Editar"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="lnkEliminar" runat="server" CausesValidation="False" OnClientClick="return confirm('Seguro que desea eliminar el registro?');"
                                    CommandName="Delete" Text="Eliminar"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="Id" HeaderText="Codigo" >
                        <ItemStyle Width="90px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="NombreSubServicio" HeaderText="Sub Servicio" >
                        <ItemStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Solicitante" HeaderText="Solicitante" >
                        <ItemStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Responsable" HeaderText="Responsable" />
                        <asp:BoundField DataField="NombreDepartamento" HeaderText="Departamento" >
                        <ItemStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="NombreMunicipio" HeaderText="Municipio" />
                        <asp:BoundField DataField="NumDictamen" HeaderText="Dictamen" />
                        <asp:BoundField DataField="FechaDictamen" HeaderText="F. Dictamen" DataFormatString="{0:d}" />
                        <asp:BoundField DataField="NumResolucion" HeaderText="Resolucion" />
                        <asp:BoundField DataField="FechaResolucion" HeaderText="F. Resolucion" DataFormatString="{0:d}" />
                        <asp:BoundField DataField="idCaja" HeaderText="Caja" />
                        <asp:BoundField DataField="NombreEstado" HeaderText="Último Estado" />
                        <asp:BoundField DataField="Encargado" HeaderText="Asignado a" />
                        <asp:ButtonField CommandName="Print" ImageUrl="~/Imagenes/PrintFile.png" Text="Imprimir"  />
                        <asp:BoundField DataField="FechaEstadoActual" HeaderText="F. Estado Actual" />
                    </Columns>
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                    <PagerStyle HorizontalAlign="Center" CssClass="pgr" />
                    <RowStyle ForeColor="Black" />
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />
                    <SortedDescendingHeaderStyle BackColor="#93451F" />
                </asp:GridView>
                <asp:Label ID="lblTotal" runat="server" Font-Bold="True"></asp:Label>
                <br />
                <br />
                <asp:HyperLink ID="linkNuevo" runat="server" NavigateUrl="~/Registro/Expediente/wfmExpediente_Add.aspx"
                    Visible="False">[linkNuevo]</asp:HyperLink>
                <asp:HyperLink ID="linkModificar" runat="server" NavigateUrl="~/Registro/Expediente/wfmExpediente_Edit.aspx"
                    Visible="False">[linkModificar]</asp:HyperLink>
                <asp:HyperLink ID="linkSeguimiento" runat="server" NavigateUrl="~/Registro/Expediente/wfmSeguimientoExpediente.aspx"
                    Visible="False">[linkSeguimiento]</asp:HyperLink>
                <br />
            </td>
            <td class="style2">
                &nbsp;</td>
        </tr>
        </table>
    </div>
        
    </div>
  <script language="javascript" type="text/javascript">
     function onEntryAdded(sender, eventArgs) {
        /* if (sender.get_count  == 0) {
             eventArgs.set_cancel(true);
         }
         else {
             $(".rddtInner").removeClass("rddtFocused");

         }*/
     }
     function OnClientEntryAdding1(sender, eventArgs) {
         var entry = eventArgs.get_entry()
         if (entry.get_value() >= 10000) {
             eventArgs.set_cancel(true);
         }
     }
     function ClientSideClick(myButton) {
         // Client side validation
         if (typeof (Page_ClientValidate) == 'function') {
             if (Page_ClientValidate() == false)
             { return false; }
         }

         //make sure the button is not of type "submit" but "button"
         if (myButton.getAttribute('type') == 'button') {
             // disable the button
             myButton.disabled = true;
             myButton.className = "btn-inactive";
             myButton.value = "procesando...";
         }
         return true;
     }
    </script>    
</asp:Content>
